export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as SolutionSection } from './SolutionSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer' 